/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CoSearchContent: typeof import('./src/components/search/CoSearchContent.vue')['default']
    CoTable: typeof import('./src/components/table/CoTable.vue')['default']
    CoTip: typeof import('./src/components/tip/CoTip.vue')['default']
  }
}
